hostname: "esx1-router.gmbros.local"

interfaces:
- name: ens192
  address: "88.99.217.246/26"
  gateway: "88.99.217.193"
  zone: internet
- name: ens224
  address: "10.0.0.1/24"
  zone: public
  routes:
  - "10.12.0.0/16 10.0.0.2"
  - "10.13.0.0/16 10.0.0.3"
- name: ens256
  address: "10.11.0.1/24"
  zone: public
- name: ens161
  address: "10.11.128.1/24"
  zone: isolated

setup_dhcp_relay: false

dnsmasq_mode: authoritative
dnsmasq_upstream_servers:
- 185.12.64.1
- 185.12.64.2

#clusters:
#- name: ocp4-simple-dynamic
#  type: simple
#  cluster_definition:
#    baseDomain: gmbros.local
#
#    controlPlaneReplicas: 3
#    computeReplicas: 2
#
#    machineNetwork:
#      cidr: 10.11.0.0/24
#
#    lbManaged: cluster
#    ingressVIP: 10.11.0.100
#    apiVIP: 10.11.0.101

# - name: ocp4-simple-static
#   type: simple
#   cluster_definition:
#     baseDomain: gmbros.local
#
#     controlPlaneReplicas: 3
#     computeReplicas: 2
#
#     machineNetwork:
#       cidr: 10.11.0.0/24
#       firstIP: 10.11.0.103
#    
#     bootstrapIP: 10.11.0.99
#
#     lbManaged: user
#     ingressVIP: 10.11.0.100
#     apiVIP: 10.11.0.101

# - name: ocp4-abi-vsphere-ha-dynamic
#   type: abi-vsphere
#   cluster_definition:
#     inventoryBaseDir: /home/sgarcia/src/ocp4-abi-vsphere-ansible/inventories
#     clusterBaseDir: ~/.local/ocp4/clusters
#
#     baseDomain: gmbros.local
#
#     controlPlaneReplicas: 3
#     computeReplicas: 2
#
#     networkType: OVNKubernetes
#     machineNetwork:
#       cidr: 10.11.0.0/24
#    
#     rendezvousIP: 10.11.0.103
#
#     lbManaged: cluster
#     ingressVIP: 10.11.0.100
#     apiVIP: 10.11.0.101
#
#     vms:
#       controlPlaneData:
#         cluster: zone1
#         cpu: 4
#         memory: 16384
#         disk:
#         - 100
#         networks:
#         - name: ens192
#           network: VM Routed Network
#         datastore: esx1-datastore
#       computeData:
#         cluster: zone1
#         cpu: 4
#         memory: 8192
#         disk:
#         - 100
#         networks:
#         - name: ens192
#           network: VM Routed Network
#         datastore: esx1-datastore
#
#     templateOverrides:
#       vms:
#         node00.ocp4-abi-vsphere-ha-dynamic.gmbros.local:
#           interfaces:
#           - name: ens192
#             ipv4:
#               address: 10.11.0.103
#               prefix-length: 24
#           dns-resolver:
#             config:
#               server:
#               - 10.11.0.1
#           gateway:
#             address: 10.11.0.1
#             interface: ens192
#            
# - name: ocp4-abi-vsphere-static
#   type: abi-vsphere
#   cluster_definition:
#     inventoryBaseDir: /home/sgarcia/src/ocp4-abi-vsphere-ansible/inventories
#     clusterBaseDir: ~/.local/ocp4/clusters
#
#     baseDomain: gmbros.local
#     controlPlaneReplicas: 3
#     computeReplicas: 2
#
#     networkType: OVNKubernetes
#     machineNetwork:
#       cidr: 10.11.0.0/24
#       gateway:
#         address: 10.11.0.1
#       dns-resolver:
#         config:
#           server:
#           - 10.11.0.1
#       firstIP: 10.11.0.103
#
#     lbManaged: cluster
#     ingressVIP: 10.11.0.100
#     apiVIP: 10.11.0.101
#
#     vms:
#       controlPlaneData:
#         cluster: zone1
#         cpu: 4
#         memory: 16384
#         disk:
#         - 100
#         networks:
#         - name: ens192
#           network: VM Routed Network
#         datastore: esx1-datastore
#       computeData:
#         cluster: zone1
#         cpu: 4
#         memory: 8192
#         disk:
#         - 100
#         networks:
#         - name: ens192
#           network: VM Routed Network
#         datastore: esx1-datastore