hostname: "esx1-router.gmbros.local"

interfaces:
- name: ens192
  address: "88.99.217.246/26"
  gateway: "88.99.217.193"
  zone: internet
- name: ens224
  address: "10.0.0.1/24"
  zone: public
  routes:
  - "10.12.0.0/16 10.0.0.2"
  - "10.13.0.0/16 10.0.0.3"
- name: ens256
  address: "10.11.0.1/24"
  zone: public
- name: ens161
  address: "10.11.128.1/24"
  zone: isolated

setup_dhcp_relay: false

dnsmasq_mode: authoritative
dnsmasq_upstream_servers:
- 185.12.64.1
- 185.12.64.2

setup_load_balancer: true
load_balancer_interface: "ens224"
load_balancer_vips:
- hostname: "api.ocp4.gmbros.local"
  vip: "10.0.0.101"
  ports:
  - 6443
  - 22623
  backend_ips:
  - 10.11.0.127
  - 10.11.0.123
  - 10.12.0.140
  - 10.13.0.125

- hostname: "apps.ocp4.gmbros.local"
  vip: "10.0.0.100"
  ports:
  - 80
  - 443
  backend_ips:
  - 10.11.0.123
  - 10.12.0.140
  - 10.13.0.125
